name: Add Labels

on:
  pull_request:
    types: opened
  issue_comment:
    types: created

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        # if: ${{ startsWith(github.event.comment.body, '/add-labels') }}
        with:
          labels: |
            automerge
            autoapprove
            dependabot-approved
            dependabot-merged
