name: Auto approve, label and auto merge

on:
  pull_request:
    types:
        - synchronize
        - opened
        - edited

jobs:
  auto-approve:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: hmarr/auto-approve-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
  auto-label:
    needs: auto-approve
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:  
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: |
          automerge
          autoapprove
          dependabot-approved
          dependabot-merged
  auto-merge:
    needs: auto-label
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
    - id: automerge
      name: automerge
      uses: "pascalgn/automerge-action@v0.16.2"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_LABELS: "automerge,dependabot-approved"
